#! /usr/bin/env bash

function _e() {
  arg=$1

  mkdir -p $LOCAL_NOTE_STORE/`echo $arg | rev | cut -d '/' -f 2- | rev`

  ${EDITOR:-vim} $LOCAL_NOTE_STORE/$arg
}

function _ls() {
  arg=$1

  tree -C $LOCAL_NOTE_STORE/$arg
}

function _rm() {
  item=$1
  echo "deleting $item"

  if [ -d $item ]; then
    rm -rf $item
    aws s3 rm s3://$NOTES_S3_BUCKET/$item --recursive --profile $NOTES_AWS_PROFILE
  else
    if [ -e $item ]; then
      rm $item
      aws s3 rm s3://$NOTES_S3_BUCKET/$item --profile $NOTES_AWS_PROFILE
    else
      echo "'$item' not found."
      exit 1
    fi
  fi
}

function _pull() {
    echo "pulling remote note store"
    aws s3 sync s3://$NOTES_S3_BUCKET $LOCAL_NOTE_STORE --profile $NOTES_AWS_PROFILE
}

function _push() {
    echo "pushing local note store to remote"
    aws s3 sync $LOCAL_NOTE_STORE s3://$NOTES_S3_BUCKET --profile $NOTES_AWS_PROFILE
}

function _render() {
  item=$LOCAL_NOTE_STORE/$1
  item_html=$item.html

  ruby -r 'github/markup' -r 'erb' -e 'md = GitHub::Markup.render_s(GitHub::Markups::MARKUP_MARKDOWN, File.read((ARGV.first))); puts ERB.new(File.read("render_md_template.html.erb")).result(binding)' $item > $item_html

  echo "rendered $item_html"
}

function _publish() {
  item=$1
  echo "publishing $item"

  if [ -d $LOCAL_NOTE_STORE/$item ]; then
    aws s3 cp $LOCAL_NOTE_STORE/$item s3://$NOTES_S3_BUCKET/$item --recursive --acl public-read --profile $NOTES_AWS_PROFILE
  else
    aws s3 cp $LOCAL_NOTE_STORE/$item s3://$NOTES_S3_BUCKET/$item --acl public-read --profile $NOTES_AWS_PROFILE
  fi
}

command=$1
arg=$2

case $command in
  pull) _pull;;
  push) _push;;
  render) _render $arg;;
  publish) _publish $arg;;
  rm) _rm $arg;;
  ls) _ls $arg;;
  e) _e $arg;;
esac

